### ISSUE TITLE
Message function unresponsiveness

### ISSUE THREAD

**Issue by sfdye** [RajanFernandez/Warmshowers#1]
1. Unable to click on any cell on the message list

2. Not loaded full messages

**Comment by RajanFernandez** [comment]
Hey, 
Sorry you haven't been able to check your messages properly. 
I can't seem to find the source of the issue and need a bit more detail to investigate the problem. 
1. Could you please check that you have to latest version installed (1.2.3) from the app store, then logout and log back in again and see if the problem still persists. If it persists, could you please make a comment here.
2. Can you please explain what you mean by not loaded full messages. Is it the messages that are not loading all their text or only a limited number of message threads being downloaded? Please provide some more detail. One limitation of the Warmshowers API is that it will only return your latest 25 message threads. If this is what you mean, then unfortunately this is not something I can fix in the app at this time.
Let's try to resolve these issues together :)
Cheers,
Raj

**Comment by sfdye** [comment]
Oops, works after re-login. Closing the issue.

**Comment by RajanFernandez** [comment]
Great! Thanks for resolving that.
