### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by grischard** [RajanFernandez/Warmshowers#4]
When logging in, I get "Incorrect username or password".

My password is 16 characters long, and contains characters like \, &, ", % and ?. Maybe they're not getting escaped properly?

**Comment by RajanFernandez** [comment]
Thanks for reporting this. 
So far (by trial and error) I've only been able to find that the & and + characters require special treatment. I will include a fix for this in the next release.
Can I ask, are there characters other than these two that you have had trouble with?

**Comment by grischard** [comment]
I haven't tried hundreds of passwords, just my one :). Maybe spaces could also be problematic? Apparently Swift has a addingPercentEncoding, which would probably not hurt if it ran on any kind of username or password string.

**Comment by RajanFernandez** [comment]
addingPercentEncoding:withAllowedCharacters: is currently used. However, if characters are encoded that are actually allowed, it will also cause problems. I have tested spaces and they are ok. 
At the moment I can see there was an issue if your password contained a & or a + character. I have tested pretty much every other character on a standard US keyboard, but can't say if characters from foreign languages would cause issues.
A fix for the problems with & and + characters will be in the next release (commit 208a52d). If you can disclose the particular non-alphanumeric characters you use in your password, then I can test these before releasing. I understand if you do not want to disclose these. However, without specifics to test against, there is not much more I can do here.

**Comment by RajanFernandez** [comment]
The fix for this issue which allows passwords can contain & or a + characters is in commit 208a52d and will be in release 1.2.5.

**Comment by grischard** [comment]
Thank you, 1.2.5 fixed it for me! I imagine that &+ should be enough.

**Comment by RajanFernandez** [comment]
Great! I'm glad you can log in now. Thanks for letting me know the fix worked.
