### ISSUE TITLE
Wishlish: export link to profile

### ISSUE THREAD

**Issue by grischard** [RajanFernandez/Warmshowers#5]
It would be useful to be able to copy a link to someone's profile to be able to send it to someone ("Should we host this person?" "I can't host this person, can you?" "Should we go there?" "Here's my profile, message me when you're in my area")

This should work on both my own profile page and on another person's profile.

**Comment by RajanFernandez** [comment]
Great idea! I've added an option to the user profile actions for this in db2b502.
Will be in version 1.5.1.
