### ISSUE TITLE
Wishlist: message field under the existing messages

### ISSUE THREAD

**Issue by grischard** [RajanFernandez/Warmshowers#6]
To message someone from the received messages, you currently need to tap their name, then tap the enveloppe on their profile page.

It would be nice if you could reply directly below the list of messages - a bit like on chat apps, or on this github issue :)

**Comment by RajanFernandez** [comment]
This is a bug. There was a reply button in the navigation bar so that you could reply straight from the message, but its seems to have got deleted from the view during one of the more recent releases. Thanks for reporting this. Will be fixed in 1.5.1.

**Comment by RajanFernandez** [comment]
Fixed in ad054dd. Will be released in version 1.5.1.
